In [1]:
import sys
import os


sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))
print(sys.path[-1])

/home/cotsios/dsit/2nd-semester/algos-in-mol-bio/py-dali


In [2]:
from src.utils import quick_load

In [3]:
BASE_DIR = os.path.dirname(os.getcwd())
REDUCED_DIRS = os.path.join(BASE_DIR, "reduced")

print("BASE_DIR:", BASE_DIR)
print("REDUCED_DIRS:", REDUCED_DIRS)

BASE_DIR: /home/cotsios/dsit/2nd-semester/algos-in-mol-bio/py-dali
REDUCED_DIRS: /home/cotsios/dsit/2nd-semester/algos-in-mol-bio/py-dali/reduced


In [4]:
sample1 = quick_load(
    os.path.join(REDUCED_DIRS, "1euv_A.pkl.gz")
)
sample1

[(np.int8(6),
  array([[49, 55],
         [50, 56],
         [51, 57],
         [52, 58],
         [53, 59],
         [54, 60]], dtype=int16),
  np.float32(5.436839),
  array([[ 9.878459 , 10.587963 , 12.35607  , 14.434559 , 15.287994 ,
          16.351904 ],
         [ 8.666962 ,  9.887051 , 10.557881 , 12.540092 , 14.272265 ,
          15.190502 ],
         [ 6.306664 ,  8.807781 ,  9.97623  , 10.833989 , 12.491376 ,
          14.312163 ],
         [ 5.0162625,  6.2587786,  8.649331 ,  9.972082 , 10.511394 ,
          12.227279 ],
         [ 5.4842963,  5.144721 ,  6.284158 ,  8.851772 ,  9.87921  ,
          10.449617 ],
         [ 3.8041785,  5.3198624,  4.943893 ,  6.301575 ,  8.583237 ,
           9.682343 ]], dtype=float32)),
 (np.int8(6),
  array([[138, 144],
         [139, 145],
         [140, 146],
         [141, 147],
         [142, 148],
         [143, 149],
         [144, 150]], dtype=int16),
  np.float32(5.40064),
  array([[10.075706 , 10.77767  , 12.752668 , 14.449834 , 